#!/bin/sh
module="driver"
device="temper"
devname="usb_device"
mode="664"

rmmod usbhid

#$* for module parameters
/sbin/insmod ./$module.ko $* || exit 1

#remove stale nodes
#rm -f /dev/${device}[0-1]

#Assuming only one device named testdrv in list -- one major number
#major=$(awk -v mod=$devname '$2 == mod {print $1}' /proc/devices)
#mknod /dev/${device}0 c $major 0

